GET http://localhost:8080/coupon/check?code=AQM2021 HTTP/1.1

###

POST http://localhost:8080/coupon HTTP/1.1
Content-Type: application/json

{
  "code": "AQM2021",
  "active": true
}

###
PUT http://localhost:8080/coupon/deactivate?id=1 HTTP/1.1