GET https://tria-software-teste-backend.herokuapp.com/coupon/check?code=AQM2021 HTTP/1.1

###

POST https://tria-software-teste-backend.herokuapp.com/coupon HTTP/1.1
Content-Type: application/json

{
  "code": "AQM2021",
  "active": true
}

###
PUT https://tria-software-teste-backend.herokuapp.com/coupon/deactivate?id=1 HTTP/1.1